### ISSUE TITLE
Enchantments showing up on randomly generated dungeon loot

### ISSUE THREAD

**Issue by SylvTheShy** [Khajiitos/PotionVapes#1]
Randomly generated swords and boots sometimes spawn with the vape enchantments.

**Comment by Khajiitos** [comment]
Thanks for noticing! This is fixed for Forge (8d51ce6ed3bffb411cad892ae3861724d96bef3a) in version 1.0.2 which I already released on CurseForge and will be available to download shortly. I'm still figuring out how to fix that on the Fabric version!

**Comment by Khajiitos** [comment]
This has been fixed in the Fabric version too! Thanks again!
