### ISSUE TITLE
vapes crash when used near other players on a server

### ISSUE THREAD

**Issue by JustNeutral0** [Khajiitos/PotionVapes#2]
[crash-2023-11-26_16.04.17-server.txt](https://github.com/Khajiitos/PotionVapes/files/13468181/crash-2023-11-26_16.04.17-server.txt)

crash when using vapes near other players on a server, something about stoppable sound in the crash causing the issue, attatched crash report from server to help

**Comment by Khajiitos** [comment]
Thanks for letting me know! This should now be fixed in the 1.0.3 update (only Forge as it only affected Forge), which will be available to download shortly.
